#!/usr/bin/env make --file

image=node-exporter
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

runargs=--network=host \
	--pid=host \
	--publish-all \
	--volume="/:/host:ro,rslave"
